name: dart_grpc_example
description: A sample command-line application.
version: 1.0.2
# homepage: https://www.example.com

environment:
  sdk: "^3.0.0"

dependencies:
  protobuf: ^3.0.0
  grpc: ^3.2.2
dev_dependencies:
  lints: ^2.1.1
  test: 1.24.4
