name: dart_grpc_example
description: A sample command-line application.
version: 1.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.7 <3.0.0'

dependencies:
  protobuf: ^2.1.0
  grpc: ^3.2.2
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

