name: grpc-gen-ts

on:
  push:
    branches:
      - main
    paths:
      - grpc-gen-ts/**/*
jobs:
  build-grpc-gen-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_TOKEN_NAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build image
        run: make -C grpc-gen-ts build

      - name: Push image
        run: make -C grpc-gen-ts push

      - name: Build ts example
        run: make -C grpc-gen-ts generate-example
