name: grpc-gen-python

on:
  push:
    branches:
      - main
    paths:
      - grpc-gen-python/**/*
jobs:
  build-grpc-gen-python:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_TOKEN_NAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Build image
        run: make -C grpc-gen-python build

      - name: Push image
        run: make -C grpc-gen-python push

      - name: Build python example
        run: make -C grpc-gen-python generate-example
